### ISSUE TITLE
Error in `reduceDimension` function due to multiple values in `@expressionFamily@vfamily`

### ISSUE THREAD

**Issue by aqlkzf** [gao-lab/GLUE#106]
### Description
When running the `reduceDimension` function on a `CellDataSet` object, an error is produced related to the `@expressionFamily@vfamily` field containing multiple values. This issue arises in the context of the `experiments/RegInf/e01_cicero.R` script.

### Steps to Reproduce
1. Create a `CellDataSet` using `newCellDataSet`.
2. Attempt to run `reduceDimension` on this dataset.

The error received is as follows:
```
Error in if (cds@expressionFamily@vfamily %in% c("negbinomial", "negbinomial.size")) { : 
  the condition has length > 1
```

Upon inspection with `print(input_cds@expressionFamily@vfamily)`, the output indicates multiple values:
```
[1] "binomialff" "VGAMglm"
```

And the class of `@vfamily` is:
```
[1] "character"
```

### Temporary Fix
As a temporary solution, manually setting the `@vfamily` to a single value resolved the issue:
```R
input_cds@expressionFamily@vfamily <- "negbinomial"
```

This change appears to allow `reduceDimension` to function without producing an error.

### Question
Is the above fix an appropriate solution for this issue, or is there an underlying problem in the `e01_cicero.R` script that requires a different approach? Could there be a step in the script where the `@expressionFamily` is incorrectly set to multiple values?

**Comment by Jeff1995** [comment]
Hi @aqlkzf. Thanks for you interest in GLUE!

The error above is likely due to version differences in `cicero`.

The version we used was [v1.8.1](https://github.com/gao-lab/GLUE/blob/fc6c2093ecc218e686586eb5fd4ea5f3e7a87e13/packrat/packrat.lock#L796), while the latest version is now v1.17.2. I can't tell whether the temporary fix would produce the same result. If the purpose was to reproduce results in the paper, I would recommend using the same version as specified in the `packrat.lock` file.
