### ISSUE TITLE
if this can be used for metabolome

### ISSUE THREAD

**Issue by lvmt** [gao-lab/GLUE#111]
hi, i read the docs "https://scglue.readthedocs.io/zh-cn/latest/data.html", and found it need the location information, so i wonder if this software can be used for spatial transcript and spatial metabolome.  

need your answer and thanks.

**Comment by Jeff1995** [comment]
Hi @lvmt. Thanks for your interest in GLUE!

Just to clarify, do you wish to integrate spatial transcript and spatial metabolome data? If that's the case, rather than following the docs, you would need to manually build some sort of guidance graph between transcripts and metabolites using prior knowledge (e.g., metabolic pathways). We have not tried anything like that, so I cannot guarantee whether the integration would be reasonable. Manual inspection of the result is advised.

It's worth noting that the spatial information would be lost when using GLUE. You might also want to check out our more recent spatial alignment method [SLAT](https://github.com/gao-lab/SLAT), which can utilize spatial information, and be used in conjunction with GLUE.

**Comment by lvmt** [comment]
Thanks for your reply, I do plan to use the software to integrate the spatial transcriptome and spatial metabolome.

I will try the software you recommended.
