### ISSUE TITLE
Questions about GLUE and CLUE's lsi operation

### ISSUE THREAD

**Issue by HelloWorldLTY** [gao-lab/GLUE#21]
Hi, I found that the LSI operation for scATAC-seq data based on dense data has some errors:
![image](https://user-images.githubusercontent.com/43333475/170202099-c76006ad-eb8b-46a0-8206-aa424eb7c826.png)
If I input an anndata with 400*1000, then I will receive such error:
![image](https://user-images.githubusercontent.com/43333475/170202221-eab528e2-1e5f-4ab8-bac4-c277b6c596f6.png)
I tried to fix it by using this operation:
![image](https://user-images.githubusercontent.com/43333475/170202423-f9d4c247-3350-4e5c-b194-9e5eaf4bb407.png)
But I meet a new bug here. Could you please help me? Thanks a lot.

**Comment by Jeff1995** [comment]
Thanks for the report! This LSI code seems to be outdated. It was throwing an error because the `sum`'s are missing `keepdims=True` arguments. You may try something like this:

```python
tf = X / X.sum(axis=1, keepdims=True)
X = tf * idf
X = X * (1e4 / X.sum(axis=1, keepdims=True))
```

Or use the current implementation [here](https://github.com/gao-lab/GLUE/blob/caa3f9d0eeb4b35ca744e68b216027634387ae82/scglue/data.py#L34).

**Comment by HelloWorldLTY** [comment]
Many thanks for your help!
