### ISSUE TITLE
error in SCGLUEModel.fit() got an unexpected keyword argument 'edge_weight'

### ISSUE THREAD

**Issue by Dan-121** [gao-lab/GLUE#60]
Hi, Zhijie:
       When I used the example from this part (https://github.com/gao-lab/GLUE/blob/master/experiments/TripleOmics/s02_glue.py), I encountered an error. Upon examining the code that encodes this part, I discovered that we do not have these parameters. I am unsure if this is a problem with the version I am using or if there is another issue.
       I would greatly appreciate your response. Thank you and I look forward to hearing back from you.
       Dan

**Comment by Jeff1995** [comment]
Thanks for the report! The case studies were conducted with v0.2.0, but the argument has since been removed in newer versions. We now require the name of edge attributes to be fixed (i.e., "weight" for edge weight, "sign" for edge sign). You may safely remove the arguments `edge_weight="weight"` and `edge_sign="sign"` and the model should work fine.
