### ISSUE TITLE
Installing package failed 

### ISSUE THREAD

**Issue by ypj1022** [gao-lab/GLUE#64]
Hi, Zhijie:
I'm so interested in GLUE .But it's my first time to use Python , I met some problems when i was installing this package.

When I installing via following step "conda install -c conda-forge -c bioconda scglue"
I get this error

```
[(base) PS C:\Users\94414> conda install -c conda-forge -c bioconda scglue
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions]
```

Then i tried installing through "pip install scglue"
I get this error

```
Collecting pysam
  Using cached pysam-0.20.0.tar.gz (4.0 MB)
    ERROR: Command errored out with exit status 1:
     command: 'e:\python 3.8.10\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\94414\\AppData\\Local\\Temp\\pip-install-81e40wk2\\pysam_889a7059fa134daea6b32885d76b2814\\setup.py'"'"'; __file
__='"'"'C:\\Users\\94414\\AppData\\Local\\Temp\\pip-install-81e40wk2\\pysam_889a7059fa134daea6b32885d76b2814\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from
 setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\94414\AppData\Local\Temp\pip-pip-egg-info-h96gmixq'
         cwd: C:\Users\94414\AppData\Local\Temp\pip-install-81e40wk2\pysam_889a7059fa134daea6b32885d76b2814\
    Complete output (23 lines):
    # pysam: no cython available - using pre-compiled C
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None

```

It's also my first time writing issue in Github.Hope I can receive your answer.
Thank you!

**Comment by Jeff1995** [comment]
Hi @ypj1022, thanks for your interest in GLUE! It's a bit unfortunate that GLUE only works on Linux and macOS, because our dependency chain contains "pysam" which doesn't seem to compile on Windows. Nevertheless, I believe you can get around this by using [WSL](https://learn.microsoft.com/en-us/windows/wsl/).

**Comment by ypj1022** [comment]
Thanks a lot for your answer @Jeff1995 ！These days I'm learing how to use WSL and still trying to install scglue.
However I  encounter new problem while installing package.

```
conda install -c conda-forge -c bioconda scglue

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): \ Killed
```
I tried a lot of ways but still couldn't solve it.
My python version is 3.8.16.

```
conda config --show
channels:
  - conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - defaults
```
Hoping for your answer again,thank you.

**Comment by Jeff1995** [comment]
There can be multiple reasons why it failed to resolve dependencies (conflict with existing packages, problematic mirrors, etc.). I would suggest the followings:

1. Create a brand new environment for installing scglue (not using the default base environment);
2. Disable third-party mirrors and use the default sources;
3. Use mamba instead of conda, which is way faster in dependency solving.

E.g., you can try using the [mambaforge](https://github.com/conda-forge/miniforge#mambaforge) distribution, and install scglue in a new environment without additional configurations:

```
mamba create -n scglue -c conda-forge -c bioconda scglue
```

**Comment by ypj1022** [comment]
Thanks a lot!!!!!!!!
I successfully install scglue by using mamba.
