### ISSUE TITLE
running CLUE on new data

### ISSUE THREAD

**Issue by jmayank23** [gao-lab/GLUE#68]
I am trying to run CLUE on other data. The number of genes in each dataset varies, but the number of features for each gene in all datasets is the same. More concretely,
Dataset - No of genes X Length of the feature vector
Dataset 1 - 100 X 1024
Dataset 2 - 500 X 1024
.
.

How can I go about running CLUE?

**Comment by Jeff1995** [comment]
Hi @jmayank23! Thanks for your interest in CLUE. But I did not fully understand the problem. Could you elaborate a bit more on the meaning of feature vector? Does it refer to the expression values in different samples/cells (i.e., each feature vector dim is a sample/cell)?

**Comment by jmayank23** [comment]
Yes

**Comment by jmayank23** [comment]
UPDATE: I have two overlapping datasets. Each sample of each of the datasets is a 1024-dimensional vector i.e., (1, 1024)

How can I train the CLUE model on this data?

**Comment by Jeff1995** [comment]
Just to make sure, as I understand, your data looks something like below:

### Dataset 1
||Cell 1|Cell 2|...|Cell 1024|
|:-:|:-:|:-:|:-:|:-:|
|Gene 1|||...||
|Gene 2|||...||
|...|...|...|...|...|
|Gene 100|||...||

### Dataset 2
||Cell 1|Cell 2|...|Cell 1024|
|:-:|:-:|:-:|:-:|:-:|
|Gene 51|||...||
|Gene 52|||...||
|...|...|...|...|...|
|Gene 550|||...||

Where, e.g., the last 50 genes of dataset 1 overlaps with the first 50 genes of dataset 2.

In that case you can roughly follow this [tutorial](https://scglue.readthedocs.io/en/latest/paired.html), with the following exceptions:

1. Your data is interpreted with genes as samples and cells as features, which is transposed compared to the conventional scenario. So you would need to store your data in a transposed manner in `AnnData`, where genes are stored as `obs`, and cells are stored as `var`. The tutorial requires paired samples to have the same `obs_names`, so you would need paired genes to have the same `obs_names`.
2. The normalization steps of `scanpy` may not be appropriate in this transposed setting. You would probably need to improvise a proper dimension reduction pipeline on your own.
3. Set the model to `SCCLUEModel` instead of `PairedSCGLUEModel`.

Let me know if there were further problems.
