### ISSUE TITLE
Unable to install on windows 10

### ISSUE THREAD

**Issue by Khalid-Usman** [gao-lab/GLUE#95]
I have created a new conda environment with python 3.10 and then run the following commands on Windows OS, but failed to install scglue.

`conda install -c conda-forge -c bioconda scglue`

or 

`pip install scglue`

Getting the following error, 

```
FileNotFoundError: [WinError 2] The system cannot find the file specified
      # pysam: no cython available - using pre-compiled C
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      # pysam: htslib configure options: None
```

**Comment by Jeff1995** [comment]
Hi @Khalid-Usman! Sorry for the late reply.

I'm afraid scglue doesn't support installing on Windows because it's dependency pybedtools, which subsequently depends on bedtools and htslib, does not support Windows. My suggestion would be to use a Linux machine or [WSL](https://learn.microsoft.com/en-us/windows/wsl/).

Please let me know if there were further issues.
